//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dispenser_API.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDevice
    {
        public int UserID { get; set; }
        public int DeviceID { get; set; }
    }
}
